### ISSUE TITLE
Handling panic errors

### ISSUE THREAD

**Issue by hitendrarao** [Djarvur/go-err113#19]
How to make panic errors wrapped static 
```
if rec := recover(); rec != nil {
	trace := debug.Stack()

	err = fmt.Errorf("PANIC [%v] TRACE[%s]", rec, string(trace))
}
```

linter error

```
err113: do not define dynamic errors, use wrapped static errors instead: "fmt.Errorf(\"PANIC [%v] TRACE[%s]\", rec, string(trace))"
```

**Comment by onokonem** [comment]
something like this

```
// on package level
var ErrPanic = errors.New("PANIC")

// in your code
if rec := recover(); rec != nil {
	trace := debug.Stack()

	err = fmt.Errorf("[%v] TRACE[%s]: %w", rec, string(trace), ErrPanic)
}
```

BTW, you do not need error for panic.

**Comment by hitendrarao** [comment]
Thanks, it worked!

The above code was from a recovery middleware on top of a rest server, that middleware will catch any handler panic and send  panic with trace to the outer handler that will log error and will send 500 to the client without breaking the server
