### ISSUE TITLE
More proofs please

### ISSUE THREAD

**Issue by Antonboom** [Djarvur/go-err113#9]
Hello!

Go 1.13 provides a mechanism for wrapping through `%w`, but this does not mean that now you can refuse libraries like https://github.com/pkg/errors, which provides a more convenient api for working with errors.

Also this absolutely does not mean that you should use `errors.Is()` everywhere instead of `==` (adding yourself an overhead for recursion). It all depends on the context of the program.

Is there anywhere documented evidence that this is how errors **should be** handled?

Nowtime it looks like a very crude idea for linter.

**Comment by onokonem** [comment]
> Is there anywhere documented evidence that this is how errors should be handled?

https://blog.golang.org/go1.13-errors

**Comment by Antonboom** [comment]
Yes, I saw this article as well as its translations.

The problem is that there is no phrase "you **should**", there is "you **can**". 

A link to the Golang repository wiki (like CodeReviewComments) would be much more interesting than a blog post, that does not contain **requirements**, but only considers the innovations of the language.

**Comment by onokonem** [comment]
You are officially allowed not to use this linter, dude!

**Comment by Antonboom** [comment]
Yes, I did.

Linters recently write all and sundry. And not all of the linters have a strong evidence base.
The presence of this raises questions and can confuse beginners in Golang.

Thanks!
